PM_SRC += chip/$(HIARCH)/pm_hal.c
PM_SRC += chip/$(HIARCH)/hal_cpu_freq.c
PM_SRC += chip/$(HIARCH)/hal_cpu_regulator.c
PM_SRC += chip/$(HIARCH)/hal_cpu_avs.c
PM_SRC += chip/$(HIARCH)/hal_media_regulator.c
PM_SRC += chip/$(HIARCH)/hal_media_avs.c
